name: ónix acevedo frómeta
favicon: null
layout_spectrum: 0.24618
typography_spectrum: 0.46349
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d87d00'
    - '#7e0305'
    - '#070802'
    - '#264800'
    - '#ffe5a7'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
