name: ónix acevedo frómeta
favicon: null
layout_spectrum: 0.75628
typography_spectrum: 0.49405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006766'
    - '#999999'
    - '#ffffff'
    - '#452122'
    - '#fe001a'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
