name: ónix acevedo frómeta
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010149'
    - '#158498'
    - '#f6fe99'
    - '#9cc86c'
    - '#552d4d'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
